import { Inter } from "next/font/google";
//import "./globals.css";
import { Themer } from "@/components";
import './animations.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="root"><Themer>{children}</Themer></div>
      </body>
    </html>
  );
}
